[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
  'npm install typescript',
  'npx tsc'
]

[start]
cmd = 'npm start'